name: Automated release creation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 4"

jobs:
  release_management:
    uses: newrelic/coreint-automation/.github/workflows/reusable_release_automation.yaml@v3
    secrets: inherit
